pretzel:
  engine: liquid
exclude:
- publish.ps1
- build.cake
- build.ps1
- tools\
- .vscode\
- .git\
- .git
- .gitignore
- add-post.cmd
- add-tag.cmd
- add-draft.cmd
- taste.cmd
- taste-drafts.cmd
- git-clean.cmd
- build.bat
- cake.config
- tests\
include:
- downloads
- .htaccess
author: Manuel Grundner
author-email: m.grundner@delegate.at
author-github: biohazard999
disqus-shortname: delegateat
main-url: https://www.delegate.at
site-name: www.delegate.at
feed-name: www.delegate.at
site-url: https://www.delegate.at
version: 0.1.0+0
commit: bb6a996a5f612474d01dd092d4023358a553ee19
last-update: 2019-09-03
